### PR TITLE
Better support for ES2015

### LINKED ISSUE #33: Uncaught TypeError: Class constructor MainWindow cannot be invoked without 'new'(…)
When targeting es2015 with typescript, I get this error...

```
Uncaught TypeError: Class constructor MainWindow cannot be invoked without 'new'(…)
  transformFunction @ riot-ts.js:52
  (anonymous function) @ riot+compiler.js:1566
  mountTo @ riot+compiler.js:2337
  pushTags @ riot+compiler.js:2459
  each @ riot+compiler.js:1883
  pushTags @ riot+compiler.js:2463
  riot.mount @ riot+compiler.js:2514
  (anonymous function) @ riot+compiler.js:3319
  done @ riot+compiler.js:3236
  compileScripts @ riot+compiler.js:3246
  (anonymous function) @ riot+compiler.js:3307
  riot.mount @ riot+compiler.js:3319(anonymous function) @ VM207:1
```

### PR DESCRIPTION
**Pull request by seanzer**
Fixes #33

### CODE REVIEW

**Comment by seanzer** [comment]
Note, this is a breaking change. opts must be passed into the base constructor in order to preserve the interface contract.

**Comment by seanzer** [comment]
Actually, alternatively, we can say the opts on the base constructor for `Riot.Element` is optional, so it's not breaking. But, I feel like it's better to be there.

**Comment by nippur72** [comment]
thanks for the PR, I am going to have a look at it. 

The only thing I am not sure is: what happens if you call riot methods during the constructor? E.g.:

``` ts
constructor(opts) {
   this.on("something", ()=>console.log("here"));
}
```

perhaps we should have a breaking change and disallow the constructor....

**Comment by seanzer** [comment]
Yea.. the timer example, e.g.

```
constructor (opts) {
  setInterval(() => {
    this.i++;
    this.update();
  }, 1000);
}
```

is probably broken by doing it this way. But I think the constructor is still useful for setting up properties from opts, which can be copied over to the tag instance. But, I think wiring up timers like this should probably be done from the mounted() callback, and then there's no issue.

Of course, feel free to find an alternative solution. This was just a suggestion 👍

**Comment by nippur72** [comment]
Ok, there are some good news: I investigated a bit searching among the past issues in the Riot repo (https://github.com/riot/riot/issues/1155, https://github.com/riot/riot/issues/771 and https://github.com/riot/riot/issues/1451), and it seems that the new Riot (3.0) will just have the feature we are looking for see: https://github.com/riot/riot/pull/1921.

So when it will be released, I'll make the necessary changes to RiotTS too (which also needs a refreshing).

**Comment by kidandcat** [comment]
+1, waiting for it :)

**Comment by seanzer** [comment]
This isn't a good solution, I'll wait for riot3+riot-ts

**Pull request closed without merging**
